_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "output/M-OWODB/t3/model_final.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  NUM_PROPOSALS: 500
  NUM_CLASSES: 81
DATASETS:
  TRAIN: ("my_train",)
  TEST:  ("my_val",)
SOLVER:
  STEPS: (5000, 10000, 12000)
  MAX_ITER: 15000
TEST:
  EVAL_PERIOD: 15000
  PREV_INTRODUCED_CLS: 40
  CUR_INTRODUCED_CLS: 20
  PREV_CLASSES: (20, 20,)
  SCORE_THRESH: 0.16
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
OUTPUT_DIR: "output/M-OWODB/t3_ft/"