_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  NUM_PROPOSALS: 500
  NUM_CLASSES: 21
  NC_WEIGHT: 0.
  CROWD: True
  CROWD_IOD: True
  CROWD_FUNCTION: "FLCG"
  CROWD_WEIGHT: 0.1
  DECORR_WEIGHT: 0.0
  CROWD_PRIVATE_HARDNESS: 0.8
DATASETS:
  TRAIN: ("my_train",)
  TEST:  ("my_val",)
SOLVER:
  STEPS: ()
  MAX_ITER: 3000
  # CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 3000
  PREV_INTRODUCED_CLS: 19
  CUR_INTRODUCED_CLS: 1
  PREV_CLASSES: (19,)
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
OUTPUT_DIR: "output/IOD_19_1/ft/"
