_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "output/S-OWODB/t4/model_final.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  NUM_PROPOSALS: 500
  NUM_CLASSES: 81
  NC_WEIGHT: 0.
DATASETS:
  TRAIN: ("my_train",)
  TEST:  ("my_val",)
SOLVER:
  STEPS: (5000, 10000, 12000)
  MAX_ITER: 15000
TEST:
  EVAL_PERIOD: 15000
  PREV_INTRODUCED_CLS: 60
  CUR_INTRODUCED_CLS: 20
  PREV_CLASSES: (19, 21, 20,)
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
OUTPUT_DIR: "output/S-OWODB/t4_ft/"